@startuml

title __ENTITIES's Class Diagram__\n

  package Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Tp_BankingOperation_SagodiraYoan_SagodiraSebastien {
    package Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Entities {
      class BankAccount {
          - id : long
          - iban : String
          - accountType : String
          - interestRate : double
          - costs : String
          + getId()
          + setId()
          + getIban()
          + setIban()
          + getAccountType()
          + setAccountType()
          + getInterestRate()
          + setInterestRate()
          + getCosts()
          + setCosts()
          + BankAccount()
          + BankAccount()
      }
    }
  }
  

  package Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Tp_BankingOperation_SagodiraYoan_SagodiraSebastien {
    package Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Entities {
      class BankingOperation {
          - id : Long
          - type : String
          - ibanSource : String
          - ibanDestination : String
          - amount : Double
          - date : Date
          + getId()
          + setId()
          + getType()
          + setType()
          + getIbanSource()
          + setIbanSource()
          + getIbanDestination()
          + setIbanDestination()
          + getAmount()
          + setAmount()
          + getDate()
          + setDate()
          + BankingOperation()
          + BankingOperation()
      }
    }
  }
  

  package Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Tp_BankingOperation_SagodiraYoan_SagodiraSebastien {
    package Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Tp_BankingOperation_SagodiraYoan_SagodiraSebastien.Entities {
      interface BankingOperationRepository {
          {abstract} + findByType()
          {abstract} + findByIbanSource()
          {abstract} + findByIbanDestination()
          {abstract} + findByDate()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
